config/routes.rb
Rails.application.routes.draw do
  resources :user_groups
  resources :user_cars #, :except => [:new]
  #get '/user_cars/:id/new', to: 'user_cars#new', as: 'new_user_car'
  resources :garages
  resources :cars
  resources :groups
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    belongs_to :garage
    has_many :user_cars
    has_many :users, through: :user_cars
end

app/models/garage.rb
class Garage < ApplicationRecord
    has_many :cars
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :user_groups
    has_many :users, through: :user_groups
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_cars
    has_many :cars, through: :user_cars
    has_many :user_groups
    has_many :groups, through: :user_groups
end

app/models/user_car.rb
class UserCar < ApplicationRecord
    belongs_to :user
    belongs_to :car

    def self.delete_by_car(car)
        joins = UserCar.where(car_id: car.id)
        joins.each {|join| join.destroy}
    end

    def self.delete_by_user(user)
        joins = UserCar.where(user_id: user.id)
        joins.each {|join| join.destroy}
    end

end

app/models/user_group.rb
class UserGroup < ApplicationRecord
    belongs_to :group
    belongs_to :user

    def self.delete_by_group(group)
        # byebug
        joins = UserGroup.where(group_id: group.id)
        joins.each {|join| join.destroy}
    end

    def self.delete_by_user(user)
        joins = UserGroup.where(user_id: user.id)
        joins.each {|join| join.destroy}
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    def index
        @cars = Car.all
    end

    def show
        @car = Car.find(params[:id])
    end

    def new
        @car = Car.new
    end

    def create
        
        @garage = Garage.find(car_params[:garage_id])
        @car = Car.create(
            make: car_params[:make], 
            model: car_params[:model],
            license_plate: car_params[:license_plate],
            garage: @garage
        )
        params[:car][:user_ids].each do |user_id| 
            UserCar.create(user_id: user_id, car: @car)
        end
        
        redirect_to car_path(@car)
    end
    
    def edit
        @car = Car.find(params[:id])
    end

    def update
        @car = Car.find(params[:id])
        
        if @car.update(car_params)
            update_user_car(@car, params[:car][:user_ids])
            flash[:success] = 'Car information updated successfully!'
        else
            flash[:errors] = 'Car information update failed'
            render :edit
        end

        redirect_to car_path(@car)
    end

    def destroy
        @car = Car.find(params[:id])
        UserCar.delete_by_car(@car)
        @car.destroy
        redirect_to cars_path, notice: "Delete Successful"
    end

    private

    def car_params
        params.require(:car).permit(:make, :model, :license_plate, :garage_id)
    end
    
    #Look up info on additional renders in private helper methods
    def update_user_car (car, new_user_ids)
        UserCar.delete_by_car(car)
        @new_list_of_drivers = new_user_ids
        @new_list_of_drivers.each do |user_id|
            updated_user_car = UserCar.new(user_id: user_id, car: car)
            updated_user_car.save
        end
    end
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController
    
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

    def show
        @group = Group.find(params[:id])
    end


    def edit
        @group = Group.find(params[:id])
    end

    def update
        @group = Group.find(params[:id])
        
        if @group.update(group_params)
    
            update_user_group(@group, params[:group][:user_ids])
            flash[:success] = 'group information updated successfully!'
        else
            flash[:errors] = 'group information update failed'
            render :edit
        end
        redirect_to group_path(@group)
    end

    def destroy
        @group = Group.find(params[:id])
        create_new_group_if_not_in_group(@group, @group.users)
        UserGroup.delete_by_group(@group)
        @group.destroy
        redirect_to users_path, notice: "Delete Successful"
    end

    private

    def group_params
        params.require(:group).permit(:name)
    end

    #Look up info on additional renders in private helper methods
    def update_user_group (group, new_user_ids)
        
        UserGroup.delete_by_group(group)
        new_user_ids.shift
        
        new_user_ids.each do |user_id|
            updated_user_group = UserGroup.new(user_id: user_id, group: group)
            updated_user_group.save
            
            puts ''
            user = User.find(user_id)
            
            delete_empty_groups(user.groups)
        end
    end

    def create_new_group_if_not_in_group(current_group, users_in_group)
        users_in_group.each do |user|
            group_joins = UserGroup.where(user: user)
            if !(group_joins.length > 1) && group_joins.length != 0
                new_group = Group.create(name: "Not in a Group")
                UserGroup.create(group: new_group, user: user)  
            end
        end
    end

    def delete_empty_groups(groups)
            empty_group = groups.select {|group| group.name == "Not in a Group"}

        if empty_group.length == 1 && empty_group.length != 0
            empty_group_join = UserGroup.find_by(group: empty_group)
            empty_group.first.destroy
            empty_group_join.destroy
        end
    end

end

app/controllers/user_cars_controller.rb
class UserCarsController < ApplicationController

    def edit
    
        @car = Car.find(params[:id])
        # render new.html.erb
    end

    def update
        
        @car = Car.find(params[:id])
    
        params[:car][:user_ids].each do |user_id| 
            UserCar.find_or_create_by(user_id: user_id, car: @car)
        end
        
        redirect_to car_path(@car)
    end

    def destroy

    end
    
    private

    def user_car_params
        params.require(:user_car).permit(:user_id, :car_id)
    end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @group = Group.create(name: "Not in a Group")
        @user = User.create(user_params)
        UserGroup.create(user: @user, group: @group)
        redirect_to user_path(@user)
    end
    
    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(name: user_params[:name])
            
            # update_user_group(@user, user_params[:user][:user_ids])
            flash[:success] = 'User information updated successfully!'
        else
            flash[:errors] = 'User information update failed'
            render :edit
        end
        redirect_to user_path(@user)
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        UserCar.delete_by_user(@user)
        redirect_to users_path, notice: "Delete Successful"
    end

    private

    def user_params
        params.require(:user).permit(:name, :user_ids,)
    end

    # def update_user_group (user, new_user_ids)
    #     UserGroup.delete_by_car(user)
    #     @new_list_of_drivers = new_user_ids
    #     @new_list_of_drivers.each do |user_id|
    #         updated_user_car = UserCar.new(user_id: user_id, car: car)
    #         updated_user_car.save
    #     end
    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/garages_helper.rb
module GaragesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/user_cars_helper.rb
module UserCarsHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/edit.html.erb
<h1>Car Form</h1>

<%= form_for(@car) do |f|%>
    <label>Car Make:</label><br>
    <%= f.text_field :make %><br>

    <label>Car Model:</label><br>
    <%= f.text_field :model %><br>

    <label>Car License Plate:</label><br>
    <%= f.text_field :license_plate %><br><br>

    <label>Parking Garage:</label><br>
    <%= collection_select(:car, :garage_id, Garage.all, :id, :name)%><br><br>
    
    <label>Select All Drivers For This Car:</label><br>
    <%= collection_check_boxes(:car, :user_ids, User.all, :id, :name) %><br>
    
    <%= f.submit %>
<% end %>

app/views/cars/index.html.erb
<% @cars.each do |car|%>
    <div><%=link_to car.make + " " + car.model, car_path(car)%></div>
<% end %>

app/views/cars/new.html.erb
<h1>Car Form</h1>

<%= form_for(@car) do |f|%>
    <label>Car Make:</label><br>
    <%= f.text_field :make %><br>

    <label>Car Model:</label><br>
    <%= f.text_field :model %><br>

    <label>Car License Plate:</label><br>
    <%= f.text_field :license_plate %><br><br>

    <label>Parking Garage:</label><br>
    <%= collection_select(:car, :garage_id, Garage.all, :id, :name)%><br><br>
    
    <label>Select All Drivers For This Car:</label><br>
    <%= collection_check_boxes(:car, :user_ids, User.all, :id, :name) %><br>

    <%= f.submit %>
<% end %>

app/views/cars/show.html.erb
<h1><%=@car.make + " " + @car.model%></h1>

<p></p>
<%=link_to "Edit", edit_car_path(@car)%><br>
<%= link_to 'Delete', car_path(@car), method: :delete, data: { confirm: 'Are you sure?' } %> 
<p></p>

<div>
    License Plate: <br>
    <%=@car.license_plate%>
</div>
<p></p>
<div>
    <%if @car.garage_id%>
        Location: <br>
        <%=@car.garage.name%>
    <%else%>
        Location: Not in a parking garage
    <%end%>
</div>
<p></p>
<div>
    Current Drivers:<br>
    <%@car.users.each do |user|%>
    <%= link_to user.name, user_path(user)%><br>
    <% end %>
</div>

app/views/groups/edit.html.erb
<h1>Group Form</h1>

    <%= form_for(@group) do |f|%>
        <label>Group Name:</label><br>
        <%= f.text_field :name%><br>
        <br>
        <label>Check box to Add or Uncheck to Remove Users:</label><br>
        <%= collection_check_boxes(:group, :user_ids, User.all, :id, :name) %><br>
        <br>
        <%= f.submit %><br>
    <% end %>
<br>
<div>
    <%= link_to "Create a New User", new_user_path %>
</div>

app/views/groups/show.html.erb
<div>
    <label>Group Account: <%=@group.name%></label><br><br>
    <%@group.users.each do |user|%>
        <%=link_to user.name, user_path(user)%><br>
    <%end%>
</div>
<br>
<div>   
    <%=link_to "Edit", edit_group_path(@group)%>
    <%= link_to 'Delete', group_path(@group), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/user_cars/edit.html.erb
<h1>Add Drivers Form</h1>

<%= form_for(@car) do |f|%>
    <label>Car Make: <%=@car.make %></label><br>
    
    <label>Car Model: <%=@car.model %></label><br>

    <label>Car License Plate: <%=@car.license_plate %></label><br><br>
    
    <label>Select Drivers You Want To Add:</label><br>
    <%= collection_check_boxes(:car, :user_ids, User.all, :id, :name) %>

    <%= f.submit %>
<% end %>

app/views/user_cars/new.html.erb
<%form_for(@user_car) do |f|%>

    <label>Select All Drivers For This Car:</label><br>
    <%= collection_select(:use_car, :user_id, User.all, :id, :name)%><br><br>
    <label>Select All Drivers For This Car:</label><br>
    
    <input name="car_id" type="hidden" value = <%@car.id%> >
    <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for(@user) do |f|%>
    <label>User name:</label><br>
    <%= f.text_field :name %><br>

    <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user|%>
    <div><%=link_to user.name, user_path(user)%></div>
<% end %>

app/views/users/new.html.erb
<div class="user_new_wrapper">
    <div class="user_new_title">
        
    </div>
    <div class="user_new_form">
        <h1>User Form</h1>
        <%= form_for(@user) do |f|%>
            <label>User name:</label><br>
            <%= f.text_field :name %><br>
            
            <%= f.submit %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<h2><%=@user.name%></h2>
<p>
    <label>My Cars:</label><br>
    <%@user.cars.each do |car|%>
        <%= link_to car.make + " " + car.model, car_path(car)%><br>
    <% end %>
</p>
<p>
    
<div>
    <label>Your Group Accounts:</label><br>
    <%@user.groups.each do |group|%>
    <%= link_to group.name, group_path(group)%><br>
    <% end %>
</div>
</p>
<div>
<%= link_to "Add New Car to Account", new_car_path%><br>
<%= link_to "Add New/Existing User to Account", edit_group_path(@user.groups.first.id)%><br>
</div>
<div>
<%=link_to "Edit User", edit_user_path(@user)%><br>
<%= link_to 'Delete User', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %> 
</div>